f = fopen('digitized data points.txt', 'w');

varNames = { ...
	'centerRadiusDegsData', ...
	'surroundRadiusDegsData', ...
	'centerGainData', ...
	'surroundGainData', ...
	'MIntGainRatio', ...
	'PIntGainRatio' ...
};

comments = { ...
	'%% Figure 4a: M cell Center Radius VS Eccentricity\n', ...
	'%% Figure 4b: M Cell Surround Radius VS Eccentricity\n', ...
	'%% Figure 5a: M Cell Center Peak Sensitivity VS Radius\n', ...
	'%% Figure 5a: M Cell Surround Peak Sensitivity VS Radius\n', ...
	'%% Figure 11: M Integrated Sensitity Surround/Center VS Eccentricity\n', ...
	'%% Figure 11: P Integrated Sensitity Surround/Center VS Eccentricity\n' ...
};

fileNames = { ...
	'fig4aM.mat', ...
	'fig4bM_Bin.mat', ...
	'fig5aMCen_Bin.mat', ...
	'fig5aMSur_Bin.mat', ...
	'fig11M.mat', ...
	'fig11P.mat' ...
};

for( k = 1 : size(filenames,2) )
	load(filenames{k});
	fprintf( f, comments{k} );
	fprintf( f, [varNames{k}, ' = [ ...\n'] );
	for( m = 1 : size(avgCal,1) )
		if( m < size(avgCal,1) )
			fprintf( f, '\t%18.12f\t%18.12f; ...\n', avgCal(m,:) );
		else
			fprintf( f, '\t%18.12f\t%18.12f ...\n', avgCal(m,:) );
		end
	end
	fprintf( f, '];\n\n' );
end


fclose(f);